version: "3.10"
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8090
    volumes:
      - .:/code
    ports:
      - 8090:8090
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: